### PR TITLE
Told make to append to build variables, to support hardened build on Debian.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Perhaps it is time to tag a new release?

**Comment by namiltd** [comment]
I think there are too few changes compared to the previous version.

**Comment by petterreinholdtsen** [comment]
[Mieczyslaw Nalewaj]
> I think there are too few changes compared to the previous version.

Why do you believe there is a minimum change requirement before a new
release can be made?  I suspect there are enough changes, and it would
bring the Debian version in line with your version, without applying
patches.  It might also bring other Linux distributions in line with the
Debian edition, assuming they use released versions.

It has been a few months since the last release.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by namiltd** [comment]
Done

**Pull request merged**
